import { useEffect, useState } from "react";
import axios from "axios";
function Orders() {
 const [orders,setOrders]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const API_URL="http://localhost:3000";
 useEffect(()=>{async function fetchOrders(){const token=localStorage.getItem("token"); if(!token){setError("Please login first");setLoading(false);return;} try {const response=await axios.get(`${API_URL}/orders`,{headers:{Authorization:`Bearer ${token}`}});setOrders(response.data.orders);}catch(error){setError(error.response?.data?.message||"Failed to load orders");}finally{setLoading(false);}} fetchOrders();},[]);
 if(loading)return <main className="page"><div className="empty-state"><h2>Loading your orders...</h2></div></main>; if(error)return <main className="page"><div className="empty-state"><h2>{error}</h2></div></main>;
 return <main className="page"><div className="page-heading"><p className="eyebrow">Your purchases</p><h1>Order history</h1><p>Track everything you’ve brought home.</p></div>{orders.length===0?<div className="empty-state"><h2>No orders yet</h2><p>Your completed orders will appear here.</p></div>:<div className="orders-list">{orders.map(order=><div key={order._id} className="order-card"><div className="order-top"><div><h3>Order #{order._id.slice(-6).toUpperCase()}</h3><p className="subtext">Placed {new Date(order.createdAt).toLocaleDateString()}</p></div><span className={`status-badge status-${order.status.toLowerCase()}`}>{order.status}</span></div>{order.products.map(item=><div key={item.productId._id} className="order-product"><img src={item.productId.image} alt={item.productId.name}/><div><h4>{item.productId.name}</h4><p>₹{item.priceAtPurchase} · Quantity {item.quantity}</p></div></div>)}<p className="order-total">Total <strong>₹{order.totalPrice}</strong></p></div>)}</div>}</main>;
}
export default Orders;
